# Version management for ZeroLimit
# This file centralizes version information

file(READ "${CMAKE_SOURCE_DIR}/VERSION" ZEROLIMIT_VERSION_STRING)
string(STRIP "${ZEROLIMIT_VERSION_STRING}" ZEROLIMIT_VERSION_STRING)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${ZEROLIMIT_VERSION_STRING}")

if(VERSION_MATCH)
    set(ZEROLIMIT_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(ZEROLIMIT_VERSION_MINOR ${CMAKE_MATCH_2})
    set(ZEROLIMIT_VERSION_PATCH ${CMAKE_MATCH_3})

    if(CMAKE_MATCH_5)
        set(ZEROLIMIT_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(ZEROLIMIT_VERSION_FULL "${ZEROLIMIT_VERSION_MAJOR}.${ZEROLIMIT_VERSION_MINOR}.${ZEROLIMIT_VERSION_PATCH}-${ZEROLIMIT_VERSION_SUFFIX}")
    else()
        set(ZEROLIMIT_VERSION_SUFFIX "")
        set(ZEROLIMIT_VERSION_FULL "${ZEROLIMIT_VERSION_MAJOR}.${ZEROLIMIT_VERSION_MINOR}.${ZEROLIMIT_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${ZEROLIMIT_VERSION_STRING}")
endif()

set(PROJECT_VERSION "${ZEROLIMIT_VERSION_MAJOR}.${ZEROLIMIT_VERSION_MINOR}.${ZEROLIMIT_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${ZEROLIMIT_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${ZEROLIMIT_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${ZEROLIMIT_VERSION_PATCH})

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(ZEROLIMIT_VERSION ${ZEROLIMIT_VERSION_FULL} PARENT_SCOPE)
endif()

message(STATUS "ZeroLimit Version: ${ZEROLIMIT_VERSION_FULL}")
message(STATUS "  Major: ${ZEROLIMIT_VERSION_MAJOR}")
message(STATUS "  Minor: ${ZEROLIMIT_VERSION_MINOR}")
message(STATUS "  Patch: ${ZEROLIMIT_VERSION_PATCH}")
if(ZEROLIMIT_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${ZEROLIMIT_VERSION_SUFFIX}")
endif()
